Simplex.Pizzaria/Areas/Administrador/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Simplex.Pizzaria.Facade;
using Simplex.Pizzaria.Models;
using SimpleX.ModelCore;

namespace Simplex.Pizzaria.Areas.Administrador.Controllers
{
    public class AdministradorController : Controller
    {
        administracaoFacade facadeAdministrador;
        cadastroFacade facadeCadastro;

        public AdministradorController()
        {
            facadeAdministrador = new administracaoFacade();
            facadeCadastro = new cadastroFacade();
        }

        // GET: Administrador/Administrador
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult usuarioListagem()
        {
            List<empresa> lstemp = facadeAdministrador.ListarEmpresa();

            usuario usuario = new usuario();
            usuario.empresaID = Guid.Parse("fc70ecab-61b8-4e53-9a99-6098b0a75a02");
            List<usuario> lstUsuario = facadeAdministrador.FiltrarUsuario(usuario);
            @ViewBag.caminho = "Usuario";

            return View(lstUsuario);
        }

        public ActionResult usuarioCadastroEdicao(string idUsuario = "")
        {
            usuario usuario = new usuario();
            if (idUsuario != "")
            {
                usuario = facadeAdministrador.ConsultarUsuario(Guid.Parse(idUsuario));
            }

            @ViewBag.caminho = "Usuario";

            return View("usuarioCadastro", usuario);
        }

        public ActionResult usuarioCadastro(string idUsuario = "")
        {
            usuario usuario = new usuario();
            if (idUsuario != "")
            {
                usuario = facadeAdministrador.ConsultarUsuario(Guid.Parse(idUsuario));
            }

            @ViewBag.caminho = "Usuario";

            return View("usuarioCadastro", usuario);
        }

        //Salvar============================================================================================
        [HttpPost]
        public ActionResult SalvarUsuario(usuario usuario)
        {
            usuario.empresaID = Guid.Parse("fc70ecab-61b8-4e53-9a99-6098b0a75a02");
            Result resultado;
            if (usuario.ID.ToString() == "" || usuario.ID == Guid.Empty)
            {
                usuario.ID = Guid.NewGuid();
                resultado = facadeAdministrador.SalvarUsuario(usuario);
            }
            else
            {
                resultado = facadeAdministrador.AlterarUsuario(usuario);
            }

            //Result resultado = facadeAdministrador.SalvarUsuario(usuario);
            if (usuario.ID != Guid.Empty)
            {
                resultado.AddMensagem("ID", usuario.ID.ToString());
                resultado.Sucesso = true;
            }

            return Json(resultado);
        }

        //Excluir============================================================================================
        public ActionResult ExcluirUsuario(string idUsuario = "")
        {
            Result resultado = new Result();

            if (idUsuario != "")
            {
                resultado = facadeAdministrador.ExcluirUsuario(Guid.Parse(idUsuario));
            }
            return Json(resultado, JsonRequestBehavior.AllowGet);
        }

    }
}

Simplex.Pizzaria/Areas/Administrador/Controllers/URAController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Simplex.Pizzaria.Facade;
using Simplex.Pizzaria.Models;

namespace Simplex.Pizzaria.Areas.Administrador.Controllers
{
    public class URAController : Controller
    {
        // GET: Administrador/URA
        public ActionResult Index()
        {
            administracaoFacade administracaoFacade = new administracaoFacade();

            //URA lstURA = administracaoFacade.ConsultarURA(Guid.Parse("4fad24d6-d9c6-496d-a7a2-b372372606da"));
            List<URA> lstURA = administracaoFacade.ListarURA();
            return View("URA", lstURA);
        }
    }
}

Simplex.Pizzaria/Areas/Administrador/Views/Administrador/usuarioCadastro.cshtml
@model Simplex.Pizzaria.Models.usuario


@{
    //ViewBag.Title = "Cadastro de Clientes";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h4>Cadastro de contato</h4>*@
<div class="tab-content">
    <div class="tab-pane active" id="horizontal-form">

        @using (Html.BeginForm("SalvarUsuario", "Administrador", FormMethod.Post, new { @class = "form-horizontal", @id = "form-usuario" }))
        {
            <div class="">
                <div class="">
                    @Html.HiddenFor(c => c.ID, new { @class = "form-control1" })
                </div>
            </div>

            <div class="">
                <div class="">
                    @Html.HiddenFor(c => c.empresaID, new { @class = "form-control1" })
                </div>
            </div>
            
            <div class="form-group">
                <label for="focusedinput" class="col-sm-2 control-label">Nome</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(c => c.nome, new { @class = "form-control1", placeholder = "Nome" })
                </div>
            </div>

            <div class="form-group">
                <label for="focusedinput" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(c => c.email, new { @class = "form-control1", placeholder = "Login" })
                </div>
            </div>

            <div class="form-group">
                <label for="focusedinput" class="col-sm-2 control-label">Senha</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(c => c.senha, new { @class = "form-control1", placeholder = "Senha" })
                </div>
            </div>


            <div class="">
                <div class="">
                    <div class="">
                        <input type="button" onclick="salvarUsuario()" class="btn-primary btn" title="Salvar" name="Salvar" value="Salvar">
                        <input type="button" onclick="cancelarUsuario()" class="btn-default btn" value="Sair">
                    </div>
                </div>
            </div>
        }
    </div>
</div>


<script src="~/Scripts/framework/jquery.simplexis.container.js"></script>
<script src="~/Scripts/framework/jquery.simplexis.usuario.js"></script>

Simplex.Pizzaria/Areas/Administrador/Views/Administrador/usuarioListagem.cshtml
@{
    ViewBag.Title = "usuarioListagem";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var detalhes = "";
    var iddiv = "";
}

@model List<Simplex.Pizzaria.Models.usuario>
@using Simplex.Pizzaria.Models

<br />
<h4>Cadastro de usuário</h4>
<div>
    <a href="javascript:ajaxContainer('/Administrador/Administrador/usuarioCadastro','divusuario')"><div class="btn btn-primary btn-float-right"><i class="fa fa-plus-circle"> Incluir novo usuario</i></div></a>
</div>
<br />
<div id="divusuario"></div>

@{
    if (Model != null)
    {
        for (var i = 0; i < Model.Count; i++)
        {
            detalhes = "";
            <div class="grid-form1">
                @*<h4>@Model[i].nome</h4>*@

                <br />
                <table class="table">
                    <tbody>
                        <tr class="table-row">
                            <td class="table-img">
                                <img src="~/images/in.jpg" alt="">
                            </td>
                            <td class="table-text">
                                <h4>@Model[i].nome</h4>


                                @if (Model[i].email != "")
                                {
                                    detalhes += "Email: " + Model[i].email + " | ";
                                }

                                <p>@detalhes</p>

                                @{
            iddiv = "iddivvendaproduto" + i;
                                }

                                <div id="@iddiv"></div>

                            </td>
                            @*<td class="march">Produto em falta no estoque</td>*@
                            <td style="width:1px">
                                <a href="javascript:ajaxContainer('/Administrador/Administrador/usuarioCadastroEdicao?idUsuario=@Model[i].ID','@iddiv')" class="btn btn-primary"><i class="fa fa-pencil"></i></a>
                                <a href="javascript:excluirUsuario('@Model[i].ID')" class="btn btn-danger"><i class="fa fa-trash"></i></a>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>

            <br />
        }
    }
}


<script src="~/Scripts/framework/jquery.simplexis.container.js"></script>
<script src="~/Scripts/framework/jquery.simplexis.usuario.js"></script>